#ifdef SHOULD_COMPILE_LOOKIN_SERVER 

//
//  LookinAttrIdentifiers.h
//  Lookin
//
//  Created by Li Kai on 2019/9/18.
//  https://lookin.work
//



#import <Foundation/Foundation.h>

#pragma mark - Group

typedef NSString * LookinAttrGroupIdentifier;

extern LookinAttrGroupIdentifier const LookinAttrGroup_None;
extern LookinAttrGroupIdentifier const LookinAttrGroup_Class;
extern LookinAttrGroupIdentifier const LookinAttrGroup_Relation;
extern LookinAttrGroupIdentifier const LookinAttrGroup_Layout;
extern LookinAttrGroupIdentifier const LookinAttrGroup_AutoLayout;
extern LookinAttrGroupIdentifier const LookinAttrGroup_ViewLayer;

extern LookinAttrGroupIdentifier const LookinAttrGroup_UIImageView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UILabel;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIControl;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIButton;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIScrollView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UITableView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UITextView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UITextField;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIVisualEffectView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIStackView;

extern LookinAttrGroupIdentifier const LookinAttrGroup_NSImageView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSControl;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSButton;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSScrollView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSTableView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSTextView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSTextField;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSVisualEffectView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSStackView;

extern LookinAttrGroupIdentifier const LookinAttrGroup_UserCustom;

#pragma mark - Section

typedef NSString * LookinAttrSectionIdentifier;

extern LookinAttrSectionIdentifier const LookinAttrSec_None;

extern LookinAttrSectionIdentifier const LookinAttrSec_UserCustom;

extern LookinAttrSectionIdentifier const LookinAttrSec_Class_Class;

extern LookinAttrSectionIdentifier const LookinAttrSec_Relation_Relation;

extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_Frame;
extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_Bounds;
extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_SafeArea;
extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_Position;
extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_AnchorPoint;

extern LookinAttrSectionIdentifier const LookinAttrSec_AutoLayout_Hugging;
extern LookinAttrSectionIdentifier const LookinAttrSec_AutoLayout_Resistance;
extern LookinAttrSectionIdentifier const LookinAttrSec_AutoLayout_Constraints;
extern LookinAttrSectionIdentifier const LookinAttrSec_AutoLayout_IntrinsicSize;

extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Visibility;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_InterationAndMasks;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Corner;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_BgColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Border;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Shadow;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Tag;

extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_ContentMode;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_TintColor;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIImageView_Name;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIImageView_Open;

extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_Text;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_NumberOfLines;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_TextColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_BreakMode;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_CanAdjustFont;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIControl_EnabledSelected;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIControl_VerAlignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIControl_HorAlignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIControl_QMUIOutsideEdge;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIButton_ContentInsets;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIButton_TitleInsets;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIButton_ImageInsets;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ContentInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_AdjustedInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_IndicatorInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_Offset;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ContentSize;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_Behavior;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ShowsIndicator;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_Bounce;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ScrollPaging;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ContentTouches;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_Zoom;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_QMUIInitialInset;

extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_SectionsNumber;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_RowsNumber;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_SeparatorStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_SeparatorColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_SeparatorInset;

extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_Basic;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_Text;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_TextColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_ContainerInset;

extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Text;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Placeholder;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_TextColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Clears;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_CanAdjustFont;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_ClearButtonMode;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIVisualEffectView_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIVisualEffectView_QMUIForegroundColor;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIStackView_Axis;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIStackView_Distribution;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIStackView_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIStackView_Spacing;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSImageView_Name;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSImageView_Open;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_State;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_ControlSize;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_Misc;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_Value;


extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_ButtonType;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_Title;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_BezelStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_Bordered;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_Transparent;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_BezelColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_ContentTintColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_ContentOffset;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_ContentSize;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_ContentInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_BorderType;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_Scroller;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_Ruler;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_LineScroll;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_PageScroll;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_ScrollElasiticity;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_Misc;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_Magnification;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_RowHeight;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AutomaticRowHeights;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_IntercellSpacing;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_ColumnAutoresizingStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_GridStyleMask;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_SelectionHighlightStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_GridColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_RowSizeStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_NumberOfRows;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_NumberOfColumns;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_UseAlternatingRowBackgroundColors;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsColumnReordering;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsColumnResizing;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsMultipleSelection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsEmptySelection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsColumnSelection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsTypeSelect;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_DraggingDestinationFeedbackStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_Autosave;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_FloatsGroupRows;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_RowActionsVisible;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_UsesStaticContents;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_UserInterfaceLayoutDirection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_VerticalMotionCanBeginDrag;


extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Basic;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_String;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_TextColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_ContainerInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_BaseWritingDirection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Size;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Resizable;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Bordered;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Bezeled;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_BezelStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Editable;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Selectable;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_DrawsBackground;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_PreferredMaxLayoutWidth;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_MaximumNumberOfLines;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_AllowsDefaultTighteningForTruncation;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_LineBreakStrategy;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Placeholder;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_TextColor;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_Material;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_InteriorBackgroundStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_BlendingMode;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_State;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_Emphasized;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_Orientation;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_EdgeInsets;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_DetachesHiddenViews;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_Distribution;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_Spacing;


#pragma mark - Attr

typedef NSString * LookinAttrIdentifier;

extern LookinAttrIdentifier const LookinAttr_None;

/// 用户自定义的
extern LookinAttrIdentifier const LookinAttr_UserCustom;

extern LookinAttrIdentifier const LookinAttr_Class_Class_Class;

extern LookinAttrIdentifier const LookinAttr_Relation_Relation_Relation;

extern LookinAttrIdentifier const LookinAttr_Layout_Frame_Frame;
extern LookinAttrIdentifier const LookinAttr_Layout_Bounds_Bounds;
extern LookinAttrIdentifier const LookinAttr_Layout_SafeArea_SafeArea;
extern LookinAttrIdentifier const LookinAttr_Layout_Position_Position;
extern LookinAttrIdentifier const LookinAttr_Layout_AnchorPoint_AnchorPoint;

extern LookinAttrIdentifier const LookinAttr_AutoLayout_Hugging_Hor;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Hugging_Ver;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Resistance_Hor;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Resistance_Ver;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Constraints_Constraints;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_IntrinsicSize_Size;

extern LookinAttrIdentifier const LookinAttr_ViewLayer_Visibility_Hidden;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Visibility_Opacity;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_InterationAndMasks_Interaction;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_InterationAndMasks_MasksToBounds;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Corner_Radius;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_BgColor_BgColor;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Border_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Border_Width;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Opacity;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Radius;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_OffsetW;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_OffsetH;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_ContentMode_Mode;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_TintColor_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_TintColor_Mode;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Tag_Tag;

extern LookinAttrIdentifier const LookinAttr_UIImageView_Name_Name;
extern LookinAttrIdentifier const LookinAttr_UIImageView_Open_Open;

extern LookinAttrIdentifier const LookinAttr_UILabel_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UILabel_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UILabel_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UILabel_NumberOfLines_NumberOfLines;
extern LookinAttrIdentifier const LookinAttr_UILabel_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UILabel_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UILabel_BreakMode_Mode;
extern LookinAttrIdentifier const LookinAttr_UILabel_CanAdjustFont_CanAdjustFont;

extern LookinAttrIdentifier const LookinAttr_UIControl_EnabledSelected_Enabled;
extern LookinAttrIdentifier const LookinAttr_UIControl_EnabledSelected_Selected;
extern LookinAttrIdentifier const LookinAttr_UIControl_VerAlignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIControl_HorAlignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIControl_QMUIOutsideEdge_Edge;

extern LookinAttrIdentifier const LookinAttr_UIButton_ContentInsets_Insets;
extern LookinAttrIdentifier const LookinAttr_UIButton_TitleInsets_Insets;
extern LookinAttrIdentifier const LookinAttr_UIButton_ImageInsets_Insets;

extern LookinAttrIdentifier const LookinAttr_UIScrollView_Offset_Offset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentSize_Size;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_AdjustedInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Behavior_Behavior;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_IndicatorInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ScrollPaging_ScrollEnabled;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ScrollPaging_PagingEnabled;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Bounce_Ver;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Bounce_Hor;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ShowsIndicator_Hor;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ShowsIndicator_Ver;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentTouches_Delay;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentTouches_CanCancel;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_MinScale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_MaxScale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_Scale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_Bounce;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_QMUIInitialInset_Inset;

extern LookinAttrIdentifier const LookinAttr_UITableView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_UITableView_SectionsNumber_Number;
extern LookinAttrIdentifier const LookinAttr_UITableView_RowsNumber_Number;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorStyle_Style;

extern LookinAttrIdentifier const LookinAttr_UITextView_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UITextView_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UITextView_Basic_Editable;
extern LookinAttrIdentifier const LookinAttr_UITextView_Basic_Selectable;
extern LookinAttrIdentifier const LookinAttr_UITextView_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UITextView_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITextView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UITextView_ContainerInset_Inset;

extern LookinAttrIdentifier const LookinAttr_UITextField_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UITextField_Placeholder_Placeholder;
extern LookinAttrIdentifier const LookinAttr_UITextField_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UITextField_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UITextField_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITextField_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UITextField_Clears_ClearsOnBeginEditing;
extern LookinAttrIdentifier const LookinAttr_UITextField_Clears_ClearsOnInsertion;
extern LookinAttrIdentifier const LookinAttr_UITextField_CanAdjustFont_CanAdjustFont;
extern LookinAttrIdentifier const LookinAttr_UITextField_CanAdjustFont_MinSize;
extern LookinAttrIdentifier const LookinAttr_UITextField_ClearButtonMode_Mode;

extern LookinAttrIdentifier const LookinAttr_UIVisualEffectView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_UIVisualEffectView_QMUIForegroundColor_Color;

extern LookinAttrIdentifier const LookinAttr_UIStackView_Axis_Axis;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Distribution_Distribution;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Spacing_Spacing;

extern LookinAttrIdentifier const LookinAttr_NSImageView_Name_Name;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Open_Open;


extern LookinAttrIdentifier const LookinAttr_NSControl_State_Enabled;
extern LookinAttrIdentifier const LookinAttr_NSControl_State_Highlighted;
extern LookinAttrIdentifier const LookinAttr_NSControl_State_Continuous;
extern LookinAttrIdentifier const LookinAttr_NSControl_ControlSize_Size;
extern LookinAttrIdentifier const LookinAttr_NSControl_Font_Name;
extern LookinAttrIdentifier const LookinAttr_NSControl_Font_Size;
extern LookinAttrIdentifier const LookinAttr_NSControl_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_WritingDirection;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_IgnoresMultiClick;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_UsesSingleLineMode;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_AllowsExpansionToolTips;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_StringValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_IntValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_IntegerValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_FloatValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_DoubleValue;
extern LookinAttrIdentifier const LookinAttr_NSButton_ButtonType_ButtonType;
extern LookinAttrIdentifier const LookinAttr_NSButton_Title_Title;
extern LookinAttrIdentifier const LookinAttr_NSButton_Title_AlernateTitle;
extern LookinAttrIdentifier const LookinAttr_NSButton_BezelStyle_BezelStyle;
extern LookinAttrIdentifier const LookinAttr_NSButton_Bordered_Bordered;
extern LookinAttrIdentifier const LookinAttr_NSButton_Transparent_Transparent;
extern LookinAttrIdentifier const LookinAttr_NSButton_BezelColor_BezelColor;
extern LookinAttrIdentifier const LookinAttr_NSButton_ContentTintColor_ContentTintColor;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_ShowsBorderOnlyWhileMouseInside;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_MaxAcceleratorLevel;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_SpringLoaded;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_HasDestructiveAction;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentOffset_Offset;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentSize_Size;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentInset_ContentInset;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentInset_AutomaticallyAdjustsContentInsets;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_BorderType_BorderType;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_AutohidesScrollers;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerStyle;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerKnobStyle;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerInsets;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Visible;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_LineScroll;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_PageScroll;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ScrollElasiticity_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ScrollElasiticity_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Misc_ScrollsDynamically;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Misc_UsesPredominantAxisScrolling;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_AllowsMagnification;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Magnification;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Max;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Min;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnReordering_AllowsColumnReordering;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnResizing_AllowsColumnResizing;
extern LookinAttrIdentifier const LookinAttr_NSTableView_ColumnAutoresizingStyle_ColumnAutoresizingStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_GridStyleMask_GridStyleMask;
extern LookinAttrIdentifier const LookinAttr_NSTableView_IntercellSpacing_IntercellSpacing;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UseAlternatingRowBackgroundColors_UseAlternatingRowBackgroundColors;
extern LookinAttrIdentifier const LookinAttr_NSTableView_GridColor_GridColor;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowSizeStyle_RowSizeStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowHeight_RowHeight;
extern LookinAttrIdentifier const LookinAttr_NSTableView_NumberOfRows_NumberOfRows;
extern LookinAttrIdentifier const LookinAttr_NSTableView_NumberOfColumns_NumberOfColumns;
extern LookinAttrIdentifier const LookinAttr_NSTableView_VerticalMotionCanBeginDrag_VerticalMotionCanBeginDrag;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsMultipleSelection_AllowsMultipleSelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsEmptySelection_AllowsEmptySelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnSelection_AllowsColumnSelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsTypeSelect_AllowsTypeSelect;
extern LookinAttrIdentifier const LookinAttr_NSTableView_SelectionHighlightStyle_SelectionHighlightStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_DraggingDestinationFeedbackStyle_DraggingDestinationFeedbackStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutomaticRowHeights_AutomaticRowHeights;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutosaveName_AutosaveName;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutosaveTableColumns_AutosaveTableColumns;
extern LookinAttrIdentifier const LookinAttr_NSTableView_FloatsGroupRows_FloatsGroupRows;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowActionsVisible_RowActionsVisible;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UsesStaticContents_UsesStaticContents;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UserInterfaceLayoutDirection_UserInterfaceLayoutDirection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Font_Name;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Font_Size;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_Editable;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_Selectable;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_RichText;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_FieldEditor;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_ImportsGraphics;
extern LookinAttrIdentifier const LookinAttr_NSTextView_String_String;
extern LookinAttrIdentifier const LookinAttr_NSTextView_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSTextView_ContainerInset_Inset;
extern LookinAttrIdentifier const LookinAttr_NSTextView_BaseWritingDirection_BaseWritingDirection;
extern LookinAttrIdentifier const LookinAttr_NSTextView_MaxSize_MaxSize;
extern LookinAttrIdentifier const LookinAttr_NSTextView_MinSize_MinSize;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Resizable_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Resizable_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Bordered_Bordered;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Bezeled_Bezeled;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Editable_Editable;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Selectable_Selectable;
extern LookinAttrIdentifier const LookinAttr_NSTextField_DrawsBackground_DrawsBackground;
extern LookinAttrIdentifier const LookinAttr_NSTextField_BezelStyle_BezelStyle;
extern LookinAttrIdentifier const LookinAttr_NSTextField_PreferredMaxLayoutWidth_PreferredMaxLayoutWidth;
extern LookinAttrIdentifier const LookinAttr_NSTextField_MaximumNumberOfLines_MaximumNumberOfLines;
extern LookinAttrIdentifier const LookinAttr_NSTextField_AllowsDefaultTighteningForTruncation_AllowsDefaultTighteningForTruncation;
extern LookinAttrIdentifier const LookinAttr_NSTextField_LineBreakStrategy_LineBreakStrategy;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Placeholder_Placeholder;
extern LookinAttrIdentifier const LookinAttr_NSTextField_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_Material_Material;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_InteriorBackgroundStyle_InteriorBackgroundStyle;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_BlendingMode_BlendingMode;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_State_State;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_Emphasized_Emphasized;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Orientation_Orientation;
extern LookinAttrIdentifier const LookinAttr_NSStackView_EdgeInsets_EdgeInsets;
extern LookinAttrIdentifier const LookinAttr_NSStackView_DetachesHiddenViews_DetachesHiddenViews;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Distribution_Distribution;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Spacing_Spacing;

#endif /* SHOULD_COMPILE_LOOKIN_SERVER */
