#ifdef SHOULD_COMPILE_LOOKIN_SERVER 

//
//  LookinAttrIdentifiers.h
//  Lookin
//
//  Created by Li Kai on 2019/9/18.
//  https://lookin.work
//



#import <Foundation/Foundation.h>

#pragma mark - Group

typedef NSString * LookinAttrGroupIdentifier;

extern LookinAttrGroupIdentifier const LookinAttrGroup_None;
extern LookinAttrGroupIdentifier const LookinAttrGroup_Class;
extern LookinAttrGroupIdentifier const LookinAttrGroup_Relation;
extern LookinAttrGroupIdentifier const LookinAttrGroup_Layout;
extern LookinAttrGroupIdentifier const LookinAttrGroup_AutoLayout;
extern LookinAttrGroupIdentifier const LookinAttrGroup_ViewLayer;

extern LookinAttrGroupIdentifier const LookinAttrGroup_UIImageView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UILabel;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIControl;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIButton;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIScrollView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UITableView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UITextView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UITextField;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIVisualEffectView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIStackView;

extern LookinAttrGroupIdentifier const LookinAttrGroup_NSImageView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSControl;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSButton;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSScrollView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSTableView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSTextView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSTextField;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSVisualEffectView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSStackView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSWindow;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSSlider;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSProgressIndicator;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSSegmentedControl;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSPopUpButton;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSComboBox;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSStepper;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSColorWell;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSSwitch;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSDatePicker;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSLevelIndicator;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSOutlineView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSCollectionView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSBox;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSSplitView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSTabView;
extern LookinAttrGroupIdentifier const LookinAttrGroup_NSGridView;

extern LookinAttrGroupIdentifier const LookinAttrGroup_UserCustom;

#pragma mark - Section

typedef NSString * LookinAttrSectionIdentifier;

extern LookinAttrSectionIdentifier const LookinAttrSec_None;

extern LookinAttrSectionIdentifier const LookinAttrSec_UserCustom;

extern LookinAttrSectionIdentifier const LookinAttrSec_Class_Class;

extern LookinAttrSectionIdentifier const LookinAttrSec_Relation_Relation;

extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_Frame;
extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_Bounds;
extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_SafeArea;
extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_Position;
extern LookinAttrSectionIdentifier const LookinAttrSec_Layout_AnchorPoint;

extern LookinAttrSectionIdentifier const LookinAttrSec_AutoLayout_Hugging;
extern LookinAttrSectionIdentifier const LookinAttrSec_AutoLayout_Resistance;
extern LookinAttrSectionIdentifier const LookinAttrSec_AutoLayout_Constraints;
extern LookinAttrSectionIdentifier const LookinAttrSec_AutoLayout_IntrinsicSize;

extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Visibility;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_InterationAndMasks;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Corner;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_BgColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Border;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Shadow;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_Tag;

extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_ContentMode;
extern LookinAttrSectionIdentifier const LookinAttrSec_ViewLayer_TintColor;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIImageView_Name;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIImageView_Open;

extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_Text;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_NumberOfLines;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_TextColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_BreakMode;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UILabel_CanAdjustFont;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIControl_EnabledSelected;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIControl_VerAlignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIControl_HorAlignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIControl_QMUIOutsideEdge;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIButton_ContentInsets;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIButton_TitleInsets;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIButton_ImageInsets;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ContentInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_AdjustedInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_IndicatorInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_Offset;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ContentSize;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_Behavior;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ShowsIndicator;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_Bounce;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ScrollPaging;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_ContentTouches;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_Zoom;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIScrollView_QMUIInitialInset;

extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_SectionsNumber;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_RowsNumber;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_SeparatorStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_SeparatorColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITableView_SeparatorInset;

extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_Basic;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_Text;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_TextColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextView_ContainerInset;

extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Text;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Placeholder;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_TextColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_Clears;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_CanAdjustFont;
extern LookinAttrSectionIdentifier const LookinAttrSec_UITextField_ClearButtonMode;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIVisualEffectView_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIVisualEffectView_QMUIForegroundColor;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIStackView_Axis;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIStackView_Distribution;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIStackView_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIStackView_Spacing;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSImageView_Name;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSImageView_Open;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSImageView_Scaling;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSImageView_Behavior;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSImageView_ContentTintColor;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_State;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_ControlSize;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_Misc;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_Value;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSControl_StringValue;


extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_ButtonType;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_Title;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_BezelStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_Bordered;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_Transparent;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_BezelColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_ContentTintColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSButton_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_ContentOffset;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_ContentSize;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_ContentInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_BorderType;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_Scroller;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_Ruler;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_LineScroll;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_PageScroll;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_ScrollElasiticity;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_Misc;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSScrollView_Magnification;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_RowHeight;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AutomaticRowHeights;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_IntercellSpacing;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_ColumnAutoresizingStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_GridStyleMask;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_SelectionHighlightStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_GridColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_RowSizeStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_NumberOfRows;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_NumberOfColumns;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_UseAlternatingRowBackgroundColors;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsColumnReordering;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsColumnResizing;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsMultipleSelection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsEmptySelection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsColumnSelection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_AllowsTypeSelect;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_DraggingDestinationFeedbackStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_Autosave;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_FloatsGroupRows;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_RowActionsVisible;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_UsesStaticContents;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_UserInterfaceLayoutDirection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTableView_VerticalMotionCanBeginDrag;


extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Font;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Basic;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_String;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_TextColor;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_ContainerInset;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_BaseWritingDirection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Size;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextView_Resizable;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Bordered;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Bezeled;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_BezelStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Editable;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Selectable;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_DrawsBackground;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_PreferredMaxLayoutWidth;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_MaximumNumberOfLines;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_AllowsDefaultTighteningForTruncation;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_LineBreakStrategy;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_Placeholder;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTextField_TextColor;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_Material;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_InteriorBackgroundStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_BlendingMode;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_State;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSVisualEffectView_Emphasized;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_Orientation;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_EdgeInsets;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_DetachesHiddenViews;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_Distribution;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_Alignment;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStackView_Spacing;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_Title;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_Subtitle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_State;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_CollectionBehavior;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_Appearance;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_TitleVisibility;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_ToolbarStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_TitlebarSeparatorStyle;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_Behavior;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_AnimationBehavior;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_Level;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_TabbingMode;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_Size;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSWindow_Info;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSSlider_SliderType;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSSlider_Range;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSSlider_TickMark;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSSlider_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSProgressIndicator_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSProgressIndicator_Range;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSProgressIndicator_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSSegmentedControl_SegmentCount;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSSegmentedControl_Selection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSSegmentedControl_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSSegmentedControl_Colors;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSPopUpButton_Behavior;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSPopUpButton_Selection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSPopUpButton_Items;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSComboBox_Items;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSComboBox_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSStepper_Range;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSStepper_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSColorWell_Color;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSColorWell_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSSwitch_State;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSDatePicker_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSDatePicker_Range;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSDatePicker_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSLevelIndicator_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSLevelIndicator_Range;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSLevelIndicator_TickMark;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSOutlineView_Indentation;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSOutlineView_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSCollectionView_Selection;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSCollectionView_Info;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSCollectionView_Colors;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSBox_Type;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSBox_Title;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSBox_Appearance;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSBox_Metrics;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSSplitView_Orientation;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSSplitView_Style;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSSplitView_Misc;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSTabView_Type;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTabView_Misc;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSTabView_Info;

extern LookinAttrSectionIdentifier const LookinAttrSec_NSGridView_Dimensions;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSGridView_Spacing;
extern LookinAttrSectionIdentifier const LookinAttrSec_NSGridView_Placement;


#pragma mark - Attr

typedef NSString * LookinAttrIdentifier;

extern LookinAttrIdentifier const LookinAttr_None;

/// 用户自定义的
extern LookinAttrIdentifier const LookinAttr_UserCustom;

extern LookinAttrIdentifier const LookinAttr_Class_Class_Class;

extern LookinAttrIdentifier const LookinAttr_Relation_Relation_Relation;

extern LookinAttrIdentifier const LookinAttr_Layout_Frame_Frame;
extern LookinAttrIdentifier const LookinAttr_Layout_Bounds_Bounds;
extern LookinAttrIdentifier const LookinAttr_Layout_SafeArea_SafeArea;
extern LookinAttrIdentifier const LookinAttr_Layout_Position_Position;
extern LookinAttrIdentifier const LookinAttr_Layout_AnchorPoint_AnchorPoint;

extern LookinAttrIdentifier const LookinAttr_AutoLayout_Hugging_Hor;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Hugging_Ver;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Resistance_Hor;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Resistance_Ver;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Constraints_Constraints;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_IntrinsicSize_Size;

extern LookinAttrIdentifier const LookinAttr_ViewLayer_Visibility_Hidden;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Visibility_Opacity;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_InterationAndMasks_Interaction;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_InterationAndMasks_MasksToBounds;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Corner_Radius;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_BgColor_BgColor;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Border_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Border_Width;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Opacity;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Radius;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_OffsetW;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_OffsetH;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_ContentMode_Mode;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_TintColor_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_TintColor_Mode;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Tag_Tag;

extern LookinAttrIdentifier const LookinAttr_UIImageView_Name_Name;
extern LookinAttrIdentifier const LookinAttr_UIImageView_Open_Open;

extern LookinAttrIdentifier const LookinAttr_UILabel_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UILabel_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UILabel_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UILabel_NumberOfLines_NumberOfLines;
extern LookinAttrIdentifier const LookinAttr_UILabel_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UILabel_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UILabel_BreakMode_Mode;
extern LookinAttrIdentifier const LookinAttr_UILabel_CanAdjustFont_CanAdjustFont;

extern LookinAttrIdentifier const LookinAttr_UIControl_EnabledSelected_Enabled;
extern LookinAttrIdentifier const LookinAttr_UIControl_EnabledSelected_Selected;
extern LookinAttrIdentifier const LookinAttr_UIControl_VerAlignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIControl_HorAlignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIControl_QMUIOutsideEdge_Edge;

extern LookinAttrIdentifier const LookinAttr_UIButton_ContentInsets_Insets;
extern LookinAttrIdentifier const LookinAttr_UIButton_TitleInsets_Insets;
extern LookinAttrIdentifier const LookinAttr_UIButton_ImageInsets_Insets;

extern LookinAttrIdentifier const LookinAttr_UIScrollView_Offset_Offset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentSize_Size;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_AdjustedInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Behavior_Behavior;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_IndicatorInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ScrollPaging_ScrollEnabled;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ScrollPaging_PagingEnabled;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Bounce_Ver;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Bounce_Hor;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ShowsIndicator_Hor;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ShowsIndicator_Ver;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentTouches_Delay;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentTouches_CanCancel;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_MinScale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_MaxScale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_Scale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_Bounce;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_QMUIInitialInset_Inset;

extern LookinAttrIdentifier const LookinAttr_UITableView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_UITableView_SectionsNumber_Number;
extern LookinAttrIdentifier const LookinAttr_UITableView_RowsNumber_Number;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorStyle_Style;

extern LookinAttrIdentifier const LookinAttr_UITextView_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UITextView_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UITextView_Basic_Editable;
extern LookinAttrIdentifier const LookinAttr_UITextView_Basic_Selectable;
extern LookinAttrIdentifier const LookinAttr_UITextView_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UITextView_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITextView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UITextView_ContainerInset_Inset;

extern LookinAttrIdentifier const LookinAttr_UITextField_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UITextField_Placeholder_Placeholder;
extern LookinAttrIdentifier const LookinAttr_UITextField_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UITextField_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UITextField_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITextField_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UITextField_Clears_ClearsOnBeginEditing;
extern LookinAttrIdentifier const LookinAttr_UITextField_Clears_ClearsOnInsertion;
extern LookinAttrIdentifier const LookinAttr_UITextField_CanAdjustFont_CanAdjustFont;
extern LookinAttrIdentifier const LookinAttr_UITextField_CanAdjustFont_MinSize;
extern LookinAttrIdentifier const LookinAttr_UITextField_ClearButtonMode_Mode;

extern LookinAttrIdentifier const LookinAttr_UIVisualEffectView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_UIVisualEffectView_QMUIForegroundColor_Color;

extern LookinAttrIdentifier const LookinAttr_UIStackView_Axis_Axis;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Distribution_Distribution;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Spacing_Spacing;

extern LookinAttrIdentifier const LookinAttr_NSImageView_Name_Name;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Open_Open;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Scaling_ImageScaling;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Scaling_ImageAlignment;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Scaling_ImageFrameStyle;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Behavior_Animates;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Behavior_Editable;
extern LookinAttrIdentifier const LookinAttr_NSImageView_ContentTintColor_ContentTintColor;


extern LookinAttrIdentifier const LookinAttr_NSControl_State_Enabled;
extern LookinAttrIdentifier const LookinAttr_NSControl_State_Highlighted;
extern LookinAttrIdentifier const LookinAttr_NSControl_State_Continuous;
extern LookinAttrIdentifier const LookinAttr_NSControl_ControlSize_Size;
extern LookinAttrIdentifier const LookinAttr_NSControl_Font_Name;
extern LookinAttrIdentifier const LookinAttr_NSControl_Font_Size;
extern LookinAttrIdentifier const LookinAttr_NSControl_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_WritingDirection;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_IgnoresMultiClick;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_UsesSingleLineMode;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_AllowsExpansionToolTips;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_StringValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_IntValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_IntegerValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_FloatValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_DoubleValue;
extern LookinAttrIdentifier const LookinAttr_NSButton_ButtonType_ButtonType;
extern LookinAttrIdentifier const LookinAttr_NSButton_Title_Title;
extern LookinAttrIdentifier const LookinAttr_NSButton_Title_AlernateTitle;
extern LookinAttrIdentifier const LookinAttr_NSButton_BezelStyle_BezelStyle;
extern LookinAttrIdentifier const LookinAttr_NSButton_Bordered_Bordered;
extern LookinAttrIdentifier const LookinAttr_NSButton_Transparent_Transparent;
extern LookinAttrIdentifier const LookinAttr_NSButton_BezelColor_BezelColor;
extern LookinAttrIdentifier const LookinAttr_NSButton_ContentTintColor_ContentTintColor;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_ShowsBorderOnlyWhileMouseInside;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_MaxAcceleratorLevel;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_SpringLoaded;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_HasDestructiveAction;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentOffset_Offset;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentSize_Size;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentInset_ContentInset;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentInset_AutomaticallyAdjustsContentInsets;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_BorderType_BorderType;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_AutohidesScrollers;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerStyle;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerKnobStyle;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerInsets;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Visible;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_LineScroll;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_PageScroll;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ScrollElasiticity_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ScrollElasiticity_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Misc_ScrollsDynamically;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Misc_UsesPredominantAxisScrolling;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_AllowsMagnification;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Magnification;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Max;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Min;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnReordering_AllowsColumnReordering;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnResizing_AllowsColumnResizing;
extern LookinAttrIdentifier const LookinAttr_NSTableView_ColumnAutoresizingStyle_ColumnAutoresizingStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_GridStyleMask_GridStyleMask;
extern LookinAttrIdentifier const LookinAttr_NSTableView_IntercellSpacing_IntercellSpacing;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UseAlternatingRowBackgroundColors_UseAlternatingRowBackgroundColors;
extern LookinAttrIdentifier const LookinAttr_NSTableView_GridColor_GridColor;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowSizeStyle_RowSizeStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowHeight_RowHeight;
extern LookinAttrIdentifier const LookinAttr_NSTableView_NumberOfRows_NumberOfRows;
extern LookinAttrIdentifier const LookinAttr_NSTableView_NumberOfColumns_NumberOfColumns;
extern LookinAttrIdentifier const LookinAttr_NSTableView_VerticalMotionCanBeginDrag_VerticalMotionCanBeginDrag;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsMultipleSelection_AllowsMultipleSelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsEmptySelection_AllowsEmptySelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnSelection_AllowsColumnSelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsTypeSelect_AllowsTypeSelect;
extern LookinAttrIdentifier const LookinAttr_NSTableView_SelectionHighlightStyle_SelectionHighlightStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_DraggingDestinationFeedbackStyle_DraggingDestinationFeedbackStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutomaticRowHeights_AutomaticRowHeights;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutosaveName_AutosaveName;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutosaveTableColumns_AutosaveTableColumns;
extern LookinAttrIdentifier const LookinAttr_NSTableView_FloatsGroupRows_FloatsGroupRows;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowActionsVisible_RowActionsVisible;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UsesStaticContents_UsesStaticContents;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UserInterfaceLayoutDirection_UserInterfaceLayoutDirection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Font_Name;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Font_Size;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_Editable;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_Selectable;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_RichText;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_FieldEditor;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_ImportsGraphics;
extern LookinAttrIdentifier const LookinAttr_NSTextView_String_String;
extern LookinAttrIdentifier const LookinAttr_NSTextView_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSTextView_ContainerInset_Inset;
extern LookinAttrIdentifier const LookinAttr_NSTextView_BaseWritingDirection_BaseWritingDirection;
extern LookinAttrIdentifier const LookinAttr_NSTextView_MaxSize_MaxSize;
extern LookinAttrIdentifier const LookinAttr_NSTextView_MinSize_MinSize;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Resizable_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Resizable_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Bordered_Bordered;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Bezeled_Bezeled;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Editable_Editable;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Selectable_Selectable;
extern LookinAttrIdentifier const LookinAttr_NSTextField_DrawsBackground_DrawsBackground;
extern LookinAttrIdentifier const LookinAttr_NSTextField_BezelStyle_BezelStyle;
extern LookinAttrIdentifier const LookinAttr_NSTextField_PreferredMaxLayoutWidth_PreferredMaxLayoutWidth;
extern LookinAttrIdentifier const LookinAttr_NSTextField_MaximumNumberOfLines_MaximumNumberOfLines;
extern LookinAttrIdentifier const LookinAttr_NSTextField_AllowsDefaultTighteningForTruncation_AllowsDefaultTighteningForTruncation;
extern LookinAttrIdentifier const LookinAttr_NSTextField_LineBreakStrategy_LineBreakStrategy;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Placeholder_Placeholder;
extern LookinAttrIdentifier const LookinAttr_NSTextField_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_NSTextField_BackgroundColor_Color;
extern LookinAttrIdentifier const LookinAttr_NSTextField_AllowsEditingTextAttributes_AllowsEditingTextAttributes;
extern LookinAttrIdentifier const LookinAttr_NSTextField_ImportsGraphics_ImportsGraphics;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_Material_Material;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_InteriorBackgroundStyle_InteriorBackgroundStyle;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_BlendingMode_BlendingMode;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_State_State;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_Emphasized_Emphasized;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Orientation_Orientation;
extern LookinAttrIdentifier const LookinAttr_NSStackView_EdgeInsets_EdgeInsets;
extern LookinAttrIdentifier const LookinAttr_NSStackView_DetachesHiddenViews_DetachesHiddenViews;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Distribution_Distribution;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Spacing_Spacing;

extern LookinAttrIdentifier const LookinAttr_NSWindow_Title_Title;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Title_Subtitle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_KeyWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_MainWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_Visible;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_CanBecomeKeyWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_CanBecomeMainWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_Titled;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_Closable;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_Miniaturizable;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_Resizable;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_UnifiedTitleAndToolbar;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_FullScreen;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_FullSizeContentView;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_UtilityWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_DocModalWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_NonactivatingPanel;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_HUDWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_CanJoinAllSpaces;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_MoveToActiveSpace;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_ParticipatesInCycle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_IgnoresCycle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenPrimary;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenAuxiliary;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenNone;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenAllowsTiling;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenDisallowsTiling;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_TitlebarAppearsTransparent;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_TitleVisibility;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_ToolbarStyle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_TitlebarSeparatorStyle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_BackgroundColor;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_AlphaValue;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_Opaque;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_HasShadow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_Movable;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_MovableByWindowBackground;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_AnimationBehavior;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_Level;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_HidesOnDeactivate;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_TabbingMode;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Size_MinSize;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Size_MaxSize;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Info_WindowNumber;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Info_BackingScaleFactor;

// UIWindowScene
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIWindowScene;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_State;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Title;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Orientation;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Windows;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Screen;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_StatusBar;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Traits;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Session;

extern LookinAttrIdentifier const LookinAttr_UIWindowScene_State_ActivationState;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Title_Title;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Orientation_InterfaceOrientation;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Windows_WindowCount;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Windows_KeyWindowClassName;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Screen_ScreenBounds;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Screen_ScreenScale;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_StatusBar_StatusBarHidden;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_StatusBar_StatusBarStyle;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_StatusBar_StatusBarFrame;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Traits_UserInterfaceStyle;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Traits_HorizontalSizeClass;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Traits_VerticalSizeClass;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Session_PersistentIdentifier;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Session_SessionRole;

// UIWindowScene
extern LookinAttrGroupIdentifier const LookinAttrGroup_UIWindowScene;

extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_State;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Title;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Orientation;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Windows;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Screen;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_StatusBar;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Traits;
extern LookinAttrSectionIdentifier const LookinAttrSec_UIWindowScene_Session;

#pragma mark - Attr

typedef NSString * LookinAttrIdentifier;

extern LookinAttrIdentifier const LookinAttr_None;

/// 用户自定义的
extern LookinAttrIdentifier const LookinAttr_UserCustom;

extern LookinAttrIdentifier const LookinAttr_Class_Class_Class;

extern LookinAttrIdentifier const LookinAttr_Relation_Relation_Relation;

extern LookinAttrIdentifier const LookinAttr_Layout_Frame_Frame;
extern LookinAttrIdentifier const LookinAttr_Layout_Bounds_Bounds;
extern LookinAttrIdentifier const LookinAttr_Layout_SafeArea_SafeArea;
extern LookinAttrIdentifier const LookinAttr_Layout_Position_Position;
extern LookinAttrIdentifier const LookinAttr_Layout_AnchorPoint_AnchorPoint;

extern LookinAttrIdentifier const LookinAttr_AutoLayout_Hugging_Hor;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Hugging_Ver;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Resistance_Hor;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Resistance_Ver;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_Constraints_Constraints;
extern LookinAttrIdentifier const LookinAttr_AutoLayout_IntrinsicSize_Size;

extern LookinAttrIdentifier const LookinAttr_ViewLayer_Visibility_Hidden;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Visibility_Opacity;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_InterationAndMasks_Interaction;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_InterationAndMasks_MasksToBounds;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Corner_Radius;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_BgColor_BgColor;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Border_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Border_Width;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Opacity;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_Radius;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_OffsetW;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Shadow_OffsetH;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_ContentMode_Mode;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_TintColor_Color;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_TintColor_Mode;
extern LookinAttrIdentifier const LookinAttr_ViewLayer_Tag_Tag;

extern LookinAttrIdentifier const LookinAttr_UIImageView_Name_Name;
extern LookinAttrIdentifier const LookinAttr_UIImageView_Open_Open;

extern LookinAttrIdentifier const LookinAttr_UILabel_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UILabel_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UILabel_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UILabel_NumberOfLines_NumberOfLines;
extern LookinAttrIdentifier const LookinAttr_UILabel_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UILabel_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UILabel_BreakMode_Mode;
extern LookinAttrIdentifier const LookinAttr_UILabel_CanAdjustFont_CanAdjustFont;

extern LookinAttrIdentifier const LookinAttr_UIControl_EnabledSelected_Enabled;
extern LookinAttrIdentifier const LookinAttr_UIControl_EnabledSelected_Selected;
extern LookinAttrIdentifier const LookinAttr_UIControl_VerAlignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIControl_HorAlignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIControl_QMUIOutsideEdge_Edge;

extern LookinAttrIdentifier const LookinAttr_UIButton_ContentInsets_Insets;
extern LookinAttrIdentifier const LookinAttr_UIButton_TitleInsets_Insets;
extern LookinAttrIdentifier const LookinAttr_UIButton_ImageInsets_Insets;

extern LookinAttrIdentifier const LookinAttr_UIScrollView_Offset_Offset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentSize_Size;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_AdjustedInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Behavior_Behavior;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_IndicatorInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ScrollPaging_ScrollEnabled;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ScrollPaging_PagingEnabled;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Bounce_Ver;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Bounce_Hor;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ShowsIndicator_Hor;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ShowsIndicator_Ver;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentTouches_Delay;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_ContentTouches_CanCancel;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_MinScale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_MaxScale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_Scale;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_Zoom_Bounce;
extern LookinAttrIdentifier const LookinAttr_UIScrollView_QMUIInitialInset_Inset;

extern LookinAttrIdentifier const LookinAttr_UITableView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_UITableView_SectionsNumber_Number;
extern LookinAttrIdentifier const LookinAttr_UITableView_RowsNumber_Number;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorInset_Inset;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITableView_SeparatorStyle_Style;

extern LookinAttrIdentifier const LookinAttr_UITextView_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UITextView_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UITextView_Basic_Editable;
extern LookinAttrIdentifier const LookinAttr_UITextView_Basic_Selectable;
extern LookinAttrIdentifier const LookinAttr_UITextView_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UITextView_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITextView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UITextView_ContainerInset_Inset;

extern LookinAttrIdentifier const LookinAttr_UITextField_Text_Text;
extern LookinAttrIdentifier const LookinAttr_UITextField_Placeholder_Placeholder;
extern LookinAttrIdentifier const LookinAttr_UITextField_Font_Name;
extern LookinAttrIdentifier const LookinAttr_UITextField_Font_Size;
extern LookinAttrIdentifier const LookinAttr_UITextField_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_UITextField_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UITextField_Clears_ClearsOnBeginEditing;
extern LookinAttrIdentifier const LookinAttr_UITextField_Clears_ClearsOnInsertion;
extern LookinAttrIdentifier const LookinAttr_UITextField_CanAdjustFont_CanAdjustFont;
extern LookinAttrIdentifier const LookinAttr_UITextField_CanAdjustFont_MinSize;
extern LookinAttrIdentifier const LookinAttr_UITextField_ClearButtonMode_Mode;

extern LookinAttrIdentifier const LookinAttr_UIVisualEffectView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_UIVisualEffectView_QMUIForegroundColor_Color;

extern LookinAttrIdentifier const LookinAttr_UIStackView_Axis_Axis;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Distribution_Distribution;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_UIStackView_Spacing_Spacing;

extern LookinAttrIdentifier const LookinAttr_NSImageView_Name_Name;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Open_Open;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Scaling_ImageScaling;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Scaling_ImageAlignment;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Scaling_ImageFrameStyle;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Behavior_Animates;
extern LookinAttrIdentifier const LookinAttr_NSImageView_Behavior_Editable;
extern LookinAttrIdentifier const LookinAttr_NSImageView_ContentTintColor_ContentTintColor;

extern LookinAttrIdentifier const LookinAttr_NSControl_State_Enabled;
extern LookinAttrIdentifier const LookinAttr_NSControl_State_Highlighted;
extern LookinAttrIdentifier const LookinAttr_NSControl_State_Continuous;
extern LookinAttrIdentifier const LookinAttr_NSControl_ControlSize_Size;
extern LookinAttrIdentifier const LookinAttr_NSControl_Font_Name;
extern LookinAttrIdentifier const LookinAttr_NSControl_Font_Size;
extern LookinAttrIdentifier const LookinAttr_NSControl_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_WritingDirection;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_IgnoresMultiClick;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_UsesSingleLineMode;
extern LookinAttrIdentifier const LookinAttr_NSControl_Misc_AllowsExpansionToolTips;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_StringValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_IntValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_IntegerValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_FloatValue;
extern LookinAttrIdentifier const LookinAttr_NSControl_Value_DoubleValue;
extern LookinAttrIdentifier const LookinAttr_NSButton_ButtonType_ButtonType;
extern LookinAttrIdentifier const LookinAttr_NSButton_Title_Title;
extern LookinAttrIdentifier const LookinAttr_NSButton_Title_AlernateTitle;
extern LookinAttrIdentifier const LookinAttr_NSButton_BezelStyle_BezelStyle;
extern LookinAttrIdentifier const LookinAttr_NSButton_Bordered_Bordered;
extern LookinAttrIdentifier const LookinAttr_NSButton_Transparent_Transparent;
extern LookinAttrIdentifier const LookinAttr_NSButton_BezelColor_BezelColor;
extern LookinAttrIdentifier const LookinAttr_NSButton_ContentTintColor_ContentTintColor;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_ShowsBorderOnlyWhileMouseInside;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_MaxAcceleratorLevel;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_SpringLoaded;
extern LookinAttrIdentifier const LookinAttr_NSButton_Misc_HasDestructiveAction;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentOffset_Offset;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentSize_Size;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentInset_ContentInset;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ContentInset_AutomaticallyAdjustsContentInsets;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_BorderType_BorderType;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_AutohidesScrollers;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerStyle;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerKnobStyle;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Scroller_ScrollerInsets;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Ruler_Visible;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_LineScroll_LineScroll;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_PageScroll_PageScroll;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ScrollElasiticity_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_ScrollElasiticity_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Misc_ScrollsDynamically;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Misc_UsesPredominantAxisScrolling;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_AllowsMagnification;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Magnification;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Max;
extern LookinAttrIdentifier const LookinAttr_NSScrollView_Magnification_Min;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnReordering_AllowsColumnReordering;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnResizing_AllowsColumnResizing;
extern LookinAttrIdentifier const LookinAttr_NSTableView_ColumnAutoresizingStyle_ColumnAutoresizingStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_GridStyleMask_GridStyleMask;
extern LookinAttrIdentifier const LookinAttr_NSTableView_IntercellSpacing_IntercellSpacing;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UseAlternatingRowBackgroundColors_UseAlternatingRowBackgroundColors;
extern LookinAttrIdentifier const LookinAttr_NSTableView_GridColor_GridColor;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowSizeStyle_RowSizeStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowHeight_RowHeight;
extern LookinAttrIdentifier const LookinAttr_NSTableView_NumberOfRows_NumberOfRows;
extern LookinAttrIdentifier const LookinAttr_NSTableView_NumberOfColumns_NumberOfColumns;
extern LookinAttrIdentifier const LookinAttr_NSTableView_VerticalMotionCanBeginDrag_VerticalMotionCanBeginDrag;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsMultipleSelection_AllowsMultipleSelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsEmptySelection_AllowsEmptySelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsColumnSelection_AllowsColumnSelection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AllowsTypeSelect_AllowsTypeSelect;
extern LookinAttrIdentifier const LookinAttr_NSTableView_SelectionHighlightStyle_SelectionHighlightStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_DraggingDestinationFeedbackStyle_DraggingDestinationFeedbackStyle;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutomaticRowHeights_AutomaticRowHeights;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutosaveName_AutosaveName;
extern LookinAttrIdentifier const LookinAttr_NSTableView_AutosaveTableColumns_AutosaveTableColumns;
extern LookinAttrIdentifier const LookinAttr_NSTableView_FloatsGroupRows_FloatsGroupRows;
extern LookinAttrIdentifier const LookinAttr_NSTableView_RowActionsVisible_RowActionsVisible;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UsesStaticContents_UsesStaticContents;
extern LookinAttrIdentifier const LookinAttr_NSTableView_UserInterfaceLayoutDirection_UserInterfaceLayoutDirection;
extern LookinAttrIdentifier const LookinAttr_NSTableView_Style_Style;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Font_Name;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Font_Size;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_Editable;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_Selectable;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_RichText;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_FieldEditor;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Basic_ImportsGraphics;
extern LookinAttrIdentifier const LookinAttr_NSTextView_String_String;
extern LookinAttrIdentifier const LookinAttr_NSTextView_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSTextView_ContainerInset_Inset;
extern LookinAttrIdentifier const LookinAttr_NSTextView_BaseWritingDirection_BaseWritingDirection;
extern LookinAttrIdentifier const LookinAttr_NSTextView_MaxSize_MaxSize;
extern LookinAttrIdentifier const LookinAttr_NSTextView_MinSize_MinSize;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Resizable_Horizontal;
extern LookinAttrIdentifier const LookinAttr_NSTextView_Resizable_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Bordered_Bordered;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Bezeled_Bezeled;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Editable_Editable;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Selectable_Selectable;
extern LookinAttrIdentifier const LookinAttr_NSTextField_DrawsBackground_DrawsBackground;
extern LookinAttrIdentifier const LookinAttr_NSTextField_BezelStyle_BezelStyle;
extern LookinAttrIdentifier const LookinAttr_NSTextField_PreferredMaxLayoutWidth_PreferredMaxLayoutWidth;
extern LookinAttrIdentifier const LookinAttr_NSTextField_MaximumNumberOfLines_MaximumNumberOfLines;
extern LookinAttrIdentifier const LookinAttr_NSTextField_AllowsDefaultTighteningForTruncation_AllowsDefaultTighteningForTruncation;
extern LookinAttrIdentifier const LookinAttr_NSTextField_LineBreakStrategy_LineBreakStrategy;
extern LookinAttrIdentifier const LookinAttr_NSTextField_Placeholder_Placeholder;
extern LookinAttrIdentifier const LookinAttr_NSTextField_TextColor_Color;
extern LookinAttrIdentifier const LookinAttr_NSTextField_BackgroundColor_Color;
extern LookinAttrIdentifier const LookinAttr_NSTextField_AllowsEditingTextAttributes_AllowsEditingTextAttributes;
extern LookinAttrIdentifier const LookinAttr_NSTextField_ImportsGraphics_ImportsGraphics;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_Material_Material;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_InteriorBackgroundStyle_InteriorBackgroundStyle;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_BlendingMode_BlendingMode;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_State_State;
extern LookinAttrIdentifier const LookinAttr_NSVisualEffectView_Emphasized_Emphasized;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Orientation_Orientation;
extern LookinAttrIdentifier const LookinAttr_NSStackView_EdgeInsets_EdgeInsets;
extern LookinAttrIdentifier const LookinAttr_NSStackView_DetachesHiddenViews_DetachesHiddenViews;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Distribution_Distribution;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Alignment_Alignment;
extern LookinAttrIdentifier const LookinAttr_NSStackView_Spacing_Spacing;

extern LookinAttrIdentifier const LookinAttr_NSWindow_Title_Title;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Title_Subtitle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_KeyWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_MainWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_Visible;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_CanBecomeKeyWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_State_CanBecomeMainWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_Titled;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_Closable;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_Miniaturizable;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_Resizable;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_UnifiedTitleAndToolbar;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_FullScreen;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_FullSizeContentView;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_UtilityWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_DocModalWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_NonactivatingPanel;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Style_HUDWindow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_CanJoinAllSpaces;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_MoveToActiveSpace;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_ParticipatesInCycle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_IgnoresCycle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenPrimary;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenAuxiliary;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenNone;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenAllowsTiling;
extern LookinAttrIdentifier const LookinAttr_NSWindow_CollectionBehavior_FullScreenDisallowsTiling;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_TitlebarAppearsTransparent;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_TitleVisibility;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_ToolbarStyle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_TitlebarSeparatorStyle;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_BackgroundColor;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_AlphaValue;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_Opaque;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Appearance_HasShadow;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_Movable;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_MovableByWindowBackground;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_AnimationBehavior;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_Level;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_HidesOnDeactivate;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Behavior_TabbingMode;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Size_MinSize;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Size_MaxSize;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Info_WindowNumber;
extern LookinAttrIdentifier const LookinAttr_NSWindow_Info_BackingScaleFactor;

// UIWindowScene
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_State_ActivationState;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Title_Title;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Orientation_InterfaceOrientation;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Windows_WindowCount;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Windows_KeyWindowClassName;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Screen_ScreenBounds;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Screen_ScreenScale;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_StatusBar_StatusBarHidden;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_StatusBar_StatusBarStyle;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_StatusBar_StatusBarFrame;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Traits_UserInterfaceStyle;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Traits_HorizontalSizeClass;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Traits_VerticalSizeClass;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Session_PersistentIdentifier;
extern LookinAttrIdentifier const LookinAttr_UIWindowScene_Session_SessionRole;

extern LookinAttrIdentifier const LookinAttr_NSSlider_SliderType_SliderType;
extern LookinAttrIdentifier const LookinAttr_NSSlider_Range_MinValue;
extern LookinAttrIdentifier const LookinAttr_NSSlider_Range_MaxValue;
extern LookinAttrIdentifier const LookinAttr_NSSlider_TickMark_NumberOfTickMarks;
extern LookinAttrIdentifier const LookinAttr_NSSlider_TickMark_TickMarkPosition;
extern LookinAttrIdentifier const LookinAttr_NSSlider_TickMark_AllowsTickMarkValuesOnly;
extern LookinAttrIdentifier const LookinAttr_NSSlider_Misc_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSSlider_Misc_KnobThickness;
extern LookinAttrIdentifier const LookinAttr_NSSlider_Misc_AltIncrementValue;
extern LookinAttrIdentifier const LookinAttr_NSSlider_Misc_TrackFillColor;

extern LookinAttrIdentifier const LookinAttr_NSProgressIndicator_Style_Style;
extern LookinAttrIdentifier const LookinAttr_NSProgressIndicator_Range_MinValue;
extern LookinAttrIdentifier const LookinAttr_NSProgressIndicator_Range_MaxValue;
extern LookinAttrIdentifier const LookinAttr_NSProgressIndicator_Range_DoubleValue;
extern LookinAttrIdentifier const LookinAttr_NSProgressIndicator_Misc_Indeterminate;
extern LookinAttrIdentifier const LookinAttr_NSProgressIndicator_Misc_Bezeled;
extern LookinAttrIdentifier const LookinAttr_NSProgressIndicator_Misc_DisplayedWhenStopped;

extern LookinAttrIdentifier const LookinAttr_NSSegmentedControl_SegmentCount_SegmentCount;
extern LookinAttrIdentifier const LookinAttr_NSSegmentedControl_Selection_SelectedSegment;
extern LookinAttrIdentifier const LookinAttr_NSSegmentedControl_Style_SegmentStyle;
extern LookinAttrIdentifier const LookinAttr_NSSegmentedControl_Style_TrackingMode;
extern LookinAttrIdentifier const LookinAttr_NSSegmentedControl_Colors_SelectedSegmentBezelColor;

extern LookinAttrIdentifier const LookinAttr_NSPopUpButton_Behavior_PullsDown;
extern LookinAttrIdentifier const LookinAttr_NSPopUpButton_Behavior_AutoenablesItems;
extern LookinAttrIdentifier const LookinAttr_NSPopUpButton_Behavior_PreferredEdge;
extern LookinAttrIdentifier const LookinAttr_NSPopUpButton_Selection_SelectedTag;
extern LookinAttrIdentifier const LookinAttr_NSPopUpButton_Selection_IndexOfSelectedItem;
extern LookinAttrIdentifier const LookinAttr_NSPopUpButton_Selection_TitleOfSelectedItem;
extern LookinAttrIdentifier const LookinAttr_NSPopUpButton_Items_NumberOfItems;

extern LookinAttrIdentifier const LookinAttr_NSComboBox_Items_NumberOfItems;
extern LookinAttrIdentifier const LookinAttr_NSComboBox_Items_HasVerticalScroller;
extern LookinAttrIdentifier const LookinAttr_NSComboBox_Items_NumberOfVisibleItems;
extern LookinAttrIdentifier const LookinAttr_NSComboBox_Items_IntercellSpacing;
extern LookinAttrIdentifier const LookinAttr_NSComboBox_Items_ItemHeight;
extern LookinAttrIdentifier const LookinAttr_NSComboBox_Misc_ButtonBordered;
extern LookinAttrIdentifier const LookinAttr_NSComboBox_Misc_Completes;
extern LookinAttrIdentifier const LookinAttr_NSComboBox_Misc_UsesDataSource;

extern LookinAttrIdentifier const LookinAttr_NSStepper_Range_MinValue;
extern LookinAttrIdentifier const LookinAttr_NSStepper_Range_MaxValue;
extern LookinAttrIdentifier const LookinAttr_NSStepper_Range_Increment;
extern LookinAttrIdentifier const LookinAttr_NSStepper_Misc_ValueWraps;
extern LookinAttrIdentifier const LookinAttr_NSStepper_Misc_Autorepeat;

extern LookinAttrIdentifier const LookinAttr_NSColorWell_Color_Color;
extern LookinAttrIdentifier const LookinAttr_NSColorWell_Misc_Bordered;
extern LookinAttrIdentifier const LookinAttr_NSColorWell_Misc_Active;
extern LookinAttrIdentifier const LookinAttr_NSColorWell_Misc_ColorWellStyle;

extern LookinAttrIdentifier const LookinAttr_NSSwitch_State_State;

extern LookinAttrIdentifier const LookinAttr_NSDatePicker_Style_DatePickerStyle;
extern LookinAttrIdentifier const LookinAttr_NSDatePicker_Style_DatePickerMode;
extern LookinAttrIdentifier const LookinAttr_NSDatePicker_Range_DateValue;
extern LookinAttrIdentifier const LookinAttr_NSDatePicker_Range_MinDate;
extern LookinAttrIdentifier const LookinAttr_NSDatePicker_Range_MaxDate;
extern LookinAttrIdentifier const LookinAttr_NSDatePicker_Misc_Bordered;
extern LookinAttrIdentifier const LookinAttr_NSDatePicker_Misc_Bezeled;
extern LookinAttrIdentifier const LookinAttr_NSDatePicker_Misc_DrawsBackground;

extern LookinAttrIdentifier const LookinAttr_NSLevelIndicator_Style_Style;
extern LookinAttrIdentifier const LookinAttr_NSLevelIndicator_Range_MinValue;
extern LookinAttrIdentifier const LookinAttr_NSLevelIndicator_Range_MaxValue;
extern LookinAttrIdentifier const LookinAttr_NSLevelIndicator_Range_WarningValue;
extern LookinAttrIdentifier const LookinAttr_NSLevelIndicator_Range_CriticalValue;
extern LookinAttrIdentifier const LookinAttr_NSLevelIndicator_TickMark_NumberOfTickMarks;
extern LookinAttrIdentifier const LookinAttr_NSLevelIndicator_TickMark_NumberOfMajorTickMarks;

extern LookinAttrIdentifier const LookinAttr_NSOutlineView_Indentation_IndentationPerLevel;
extern LookinAttrIdentifier const LookinAttr_NSOutlineView_Misc_AutoresizesOutlineColumn;
extern LookinAttrIdentifier const LookinAttr_NSOutlineView_Misc_IndentationMarkerFollowsCell;
extern LookinAttrIdentifier const LookinAttr_NSOutlineView_Misc_AutosaveExpandedItems;

extern LookinAttrIdentifier const LookinAttr_NSCollectionView_Selection_Selectable;
extern LookinAttrIdentifier const LookinAttr_NSCollectionView_Selection_AllowsMultipleSelection;
extern LookinAttrIdentifier const LookinAttr_NSCollectionView_Selection_AllowsEmptySelection;
extern LookinAttrIdentifier const LookinAttr_NSCollectionView_Info_NumberOfSections;
extern LookinAttrIdentifier const LookinAttr_NSCollectionView_Colors_BackgroundColors;

extern LookinAttrIdentifier const LookinAttr_NSBox_Type_BoxType;
extern LookinAttrIdentifier const LookinAttr_NSBox_Type_BorderType;
extern LookinAttrIdentifier const LookinAttr_NSBox_Title_Title;
extern LookinAttrIdentifier const LookinAttr_NSBox_Title_TitlePosition;
extern LookinAttrIdentifier const LookinAttr_NSBox_Appearance_Transparent;
extern LookinAttrIdentifier const LookinAttr_NSBox_Appearance_FillColor;
extern LookinAttrIdentifier const LookinAttr_NSBox_Appearance_BorderColor;
extern LookinAttrIdentifier const LookinAttr_NSBox_Metrics_BorderWidth;
extern LookinAttrIdentifier const LookinAttr_NSBox_Metrics_CornerRadius;
extern LookinAttrIdentifier const LookinAttr_NSBox_Metrics_ContentViewMargins;

extern LookinAttrIdentifier const LookinAttr_NSSplitView_Orientation_Vertical;
extern LookinAttrIdentifier const LookinAttr_NSSplitView_Style_DividerStyle;
extern LookinAttrIdentifier const LookinAttr_NSSplitView_Style_DividerThickness;
extern LookinAttrIdentifier const LookinAttr_NSSplitView_Misc_ArrangesAllSubviews;

extern LookinAttrIdentifier const LookinAttr_NSTabView_Type_TabViewType;
extern LookinAttrIdentifier const LookinAttr_NSTabView_Type_TabPosition;
extern LookinAttrIdentifier const LookinAttr_NSTabView_Type_TabViewBorderType;
extern LookinAttrIdentifier const LookinAttr_NSTabView_Misc_AllowsTruncatedLabels;
extern LookinAttrIdentifier const LookinAttr_NSTabView_Misc_DrawsBackground;
extern LookinAttrIdentifier const LookinAttr_NSTabView_Info_NumberOfTabViewItems;

extern LookinAttrIdentifier const LookinAttr_NSGridView_Dimensions_NumberOfColumns;
extern LookinAttrIdentifier const LookinAttr_NSGridView_Dimensions_NumberOfRows;
extern LookinAttrIdentifier const LookinAttr_NSGridView_Spacing_RowSpacing;
extern LookinAttrIdentifier const LookinAttr_NSGridView_Spacing_ColumnSpacing;
extern LookinAttrIdentifier const LookinAttr_NSGridView_Placement_XPlacement;
extern LookinAttrIdentifier const LookinAttr_NSGridView_Placement_YPlacement;

#endif /* SHOULD_COMPILE_LOOKIN_SERVER */
